config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users

  namespace :epsadmin do 
    resources :merchants do
    get '/merchant_status' => "merchants#merchant_status_check"
     get '/transaction' => "merchants#transaction",:as => :transaction
    get '/transaction_status' => "merchants#transaction_status_check"
      resources :invoices
     get '/invoice_status' => "invoices#invoice_status_check"
      resources :devices do 
         get '/device_status' => "devices#device_status_check"
      end
    end

    post 'admins/update_user_status' => 'admins#update_user_status'
    resources :admins
  end

  get 'admin_dashboard/all_device'
  get 'admin_dashboard/all_invoice'
  get 'admin_dashboard/individual_device/:id' => "admin_dashboard#individual_device",:as => :individual_device, via: [:get,:post]

  get 'dashboard/index'
  get 'dashboard/transaction'
  get 'dashboard/billing'
  get '/dashboard/billing_individual/:id' => 'dashboard#billing_individual', :as => :dashboard_billing_individual 
  get 'dashboard/merchant_detail'
  post '/dashboard/update_transaction' => 'dashboard#update_transaction'
  get '/dashboard/transaction_cancel/:id' => 'dashboard#transaction_cancel', :as => :dashboard_transaction_cancel


  ##API RELATED ROUTES
  namespace :api do
    namespace :v1 do
      #get "/falconplus/validate_device" => "falcon_plus#validate_device"
      post "/falconplus/send_otp"=>"falcon_plus#send_otp"
      post "/falconplus/save_customer"=>"falcon_plus#save_customer"
      post "/falconplus/create_transaction"=>"falcon_plus#create_transaction"
      get "/falconplus/get_transaction_by_id"=>"falcon_plus#get_transaction_by_id"
      post "/falconplus/update_transaction_by_id"=>"falcon_plus#update_transaction_by_id"
      #get "/falconplus/pending_transaction_by_code"=>"falcon_plus#pending_transaction_by_code"
      #get "/falconplus/pending_transaction_by_terminal_id"=>"falcon_plus#pending_transaction_by_terminal_id"
      #get "/falconplus/pending_transaction_by_id"=>"falcon_plus#pending_transaction_by_id"
      
     # match "/falconplus/update_transaction_by_terminal_id"=>"falcon_plus#update_transaction_by_terminal_id", via: [:put,:post]
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :get_merchant
  
  def index
    @transaction = @merchant.transactions.where(:transaction_status => 'pending')
    respond_to do |format|
      format.html
      format.json { render json: @transaction }
    end
  end

  def transaction
    @merchant_transaction = @merchant.transactions
    respond_to do |format|
      format.html
      format.json { render json: @merchant_transaction }
    end
  end

  def billing
    @subscription = @merchant.subscription
    @merchant_billing = @subscription.invoices
    respond_to do |format|
      format.html
      format.json { render json: @merchant_billing }
    end
  end

  def billing_individual
    @billing_individual = Invoice.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @billing_individual }
    end
  end

  def merchant_detail
    @merchant_device = @merchant.devices
    respond_to do |format|
      format.html
      format.json { render :json => {:merchant_detail => @merchant, merchant_device => @merchant_device }}
    end
  end

  def update_transaction
    @update_transaction = Transaction.find(params[:tid])
    @update_transaction.update_attributes(:payment_timestamp => params[:date] ,:transaction_details => params[:details], :transaction_type =>  params[:type],:transaction_status => "paid")
    respond_to do |format|
      format.html { redirect_to dashboard_transaction_path, notice: 'Status was successfully updated.'}
      format.json { head :no_content }
    end
  end

  def transaction_cancel
    @transaction_cancel = Transaction.find(params[:id])
    @transaction_cancel.update_attributes(:transaction_status => "cancelled")
    respond_to do |format|
      format.html { redirect_to dashboard_transaction_path, notice: 'Status was successfully updated.'}
      format.json { head :no_content }
    end
  end


  private

  def get_merchant
    @merchant = current_user.merchant
    if @merchant.nil?
      redirect_to "/", :notice => "Sorry you are authorized for this page."
      return
    end
  end
  

end

app/helpers/dashboard_helper.rb
module DashboardHelper

def get_transaction_amount(st,en)
stcol = "["
trns = Transaction.collection.aggregate([{"$match"=>{"transaction_timestamp"=>{"$gt"=>Time.now-1.month,"$lt"=>Time.now},"transaction_status" => "paid", "merchant_id" => current_user.merchant.id}},{"$group"=>{"_id"=>{"year"=>{"$year"=>"$transaction_timestamp"},"month"=>{ "$month"=>"$transaction_timestamp"},"day"=>{"$dayOfMonth"=>"$transaction_timestamp"}},"total" => {"$sum" => "$amount"}}}])
trns.each_with_index do |t,i| 
	puts t.inspect
   stcol << (i==0 ? "[" : ",[")
   stcol << "Date.UTC(#{t["_id"]["year"]},#{((t["_id"]["month"]).to_i - 1)},#{t["_id"]["day"]}), #{t["total"]}"
   stcol << "]"
end 
stcol << "]"
end

def get_transaction_amount_total(st,en)
	amt = Transaction.where(:merchant_id => current_user.merchant.id).where(:transaction_timestamp => st..en).where(:transaction_status => "paid").sum :amount
	return amt
end

def get_transaction_count(st,en)
stcol = "["
trns = Transaction.collection.aggregate([{"$match"=>{"transaction_timestamp"=>{"$gt"=>Time.now-1.month,"$lt"=>Time.now}, "merchant_id" => current_user.merchant.id}},{"$group"=>{"_id"=>{"year"=>{"$year"=>"$transaction_timestamp"},"month"=>{ "$month"=>"$transaction_timestamp"},"day"=>{"$dayOfMonth"=>"$transaction_timestamp"}},"total" => {"$sum" => 1}}}])
trns.each_with_index do |t,i| 
	puts t.inspect
   stcol << (i==0 ? "[" : ",[")
   stcol << "Date.UTC(#{t["_id"]["year"]},#{((t["_id"]["month"]).to_i - 1)},#{t["_id"]["day"]}), #{t["total"]}"
   stcol << "]"
end 
stcol << "]"
end

def get_transaction_count_total(st,en)
	cnt = Transaction.where(:merchant_id => current_user.merchant.id).where(:transaction_timestamp => st..en).count
	return cnt
end

end

app/views/dashboard/billing.html.erb
<section>
  <div class="container">
    <div class="padding_inner">
      <h1>Billing</h1>          
      <div class="merchant_table table-responsive billing_table">
          <table class="display table text-center" id="merchant_invoice">
            <thead>
              <tr>
                  <th>Invoice Id</th>
                  <th>Date</th>
                  <th>Amount</th>
                  <th>Type</th>
                  <th>status</th>
              </tr>
            </thead>
            <tbody>
              <% @merchant_billing.each do |invoice| %>
                <tr>
                  <td align="center"><%= link_to invoice.invoice_number, dashboard_billing_individual_path(invoice.id)%></td>
                  <td align="center"><%= invoice.invoice_date.strftime("%d/%m/%y") %></td>
                  <td align="center"><%= invoice.invoice_amount %></td>
                  <td align="center"><%= invoice.invoice_type.upcase unless invoice.invoice_type.nil? %></td>
                  <% if invoice.status == "pending" || invoice.status == "cancelled" %>
                    <td align="center" class="pending">
                        <%= invoice.status.upcase unless invoice.status.nil? %>
                    </td>
                <% else %>
                    <td align="center" class="active">
                        <%= invoice.status.upcase unless invoice.status.nil? %>
                    </td>
                <% end %>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
    </div>
  </div>
</section>


<script type="text/javascript">
  $('#merchant_invoice').dataTable();
  bJQueryUI: true;
</script>

app/views/dashboard/billing_individual.html.erb
<section>
	<div class="container">
		<div class="padding_inner details_lookup">
	  		<h1>Billing Individual (<%=@billing_individual.invoice_number%>)</h1>
  			<div class="clearfix"></div>
	  		<!--tab_menu ends-->	
	  		<div class="table_outer">
		  		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				  	<div class="merchant_details">
				  		<div class="row">			  		
					  		<table>
					  			<tr>
					  				<td>
					  					Invoice Number: 
									</td>
					  				</td>
					  				<td><%=@billing_individual.invoice_number%></td>
					  			</tr>
								<tr>
					  				<td>
					  					Invoice Date: 
					  				</td>
					  				<td><%= @billing_individual.invoice_date.strftime("%d/%m/%y") unless  @billing_individual.invoice_date.nil? %></td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Business Name: 
					  				</td>
					  				<td><%=@billing_individual.business_name%></td>
					  			</tr>	
					  			<tr>
					  				<td class="add_top">
					  					Address:  
					  				</td>
					  				<td><%=@billing_individual.address%></td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Amount: 
					  				</td>
					  				<td><%= @billing_individual.invoice_amount %></td>
					  			</tr>	
					  			<tr>
					  				<td>
			  							Tax:  
			  						</td>
			  						<td>
			  							<%= @billing_individual.tax %>
			  						</td>
					  			</tr>		  					  			
							</table>
				  		</div>
			  		</div>
			  	</div>

			  	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				  	<div class="merchant_details">
				  		<div class="row">			  		
					  		<table>
					  			<tr>
					  				<td>
					  					Invoice Type: 
									</td>
					  				<td><%= @billing_individual.invoice_type %></td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Status: 
				  					</td>
					  				<td>
					  					<% if @billing_individual.status == "pending" || @billing_individual.status == "cancelled" %>
							  				<span class="pending">
							  					<%= @billing_individual.status.upcase unless @billing_individual.status.nil? %>
							  				</span> 
										<% else %>
							  				<span class="active">
							  					<%= @billing_individual.status.upcase unless @billing_individual.status.nil? %>
											</span>
										<% end %>
					  				</td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Paid Date: 
					  				</td>
					  				<td><%= @billing_individual.paid_date %></td>
					  			</tr>	
					  			<tr>
					  				<td>
					  					Payment Details: 
					  				</td>
					  				<td><%= @billing_individual.payment_details %></td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Remarks: 
					  				</td>
					  				<td><%= @billing_individual.remarks %></td>
					  			</tr>			  					  			
							</table>
				  		</div>
		  			</div>
			  	</div>	
	  		</div><!--table_outer ends-->
		</div>
	</div>
</section> 
     <%= link_to 'Back', dashboard_billing_path %>

app/views/dashboard/index.html.erb
<section>
  	<div class="container">
  		<div class="padding_inner">
	  		<h1>Dashboard</h1>	
	  		<h3>Pending Transactions</h3>
	  		<div class="merchant_table table-responsive dashboard_pending">
		  		<table class="display table text-center" id="merchant_index">
		  			<thead>
						<tr>
							<th>
								Date
							</th>
							<th>
								Amount
							</th>
							<th>
								Status
							</th>
							<th>
								Device
							</th>
							<th>
								Mark As
							</th>
						</tr>
					</thead>
					<tbody>
						<% @transaction.each do |transaction_list| %>
							<tr>
								<td align="center">
									<%= transaction_list.transaction_timestamp.strftime("%d %b %Y") unless transaction_list.transaction_timestamp.nil? %>
								</td>
								<td align="center">
									<%= transaction_list.amount %>
								</td>
								<% if transaction_list.transaction_status == "paid" %>
									<td align="center" class="active">
										<%= transaction_list.transaction_status.upcase unless transaction_list.transaction_status.nil? %>
									</td>
								<% else %>
									<td align="center" class="pending">
										<%= transaction_list.transaction_status.upcase unless transaction_list.transaction_status.nil? %>
									</td>
								<% end %>
								<td align="center">
									<%= transaction_list.device.device_serial_number %>
								</td>
				  				<td>
				  					<div class="button_device">
					  					<% if transaction_list.transaction_status == "pending"%>
											<span style="cursor: pointer;" onClick="pop('popDiv')" class="popup btn btn-success" id="<%=transaction_list.id%>">Paid</span>

											<%= link_to 'Cancelled',{:controller => :dashboard, :action => :transaction_cancel, :id => transaction_list.id},:class=> "btn btn-danger" , data: {confirm: "Are you sure!"} %>
										<% end %>
								  	</div>
							  	</td>
						  	</tr>
					  	<% end %>
					</tbody>				  						  			
		  		</table>
		  	</div><!--table ends-->

		  	<div class="dashboard_outer">
		  		<div class="row">
		  			<div class="top_space">
				  		<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">	
				  			<h3>Transactions Executed In Last Month</h3>
							<div id="chart" style="width:100%; height:400px;"></div>
				  		</div>			  		
				  		<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
				  			<h3>Total Transactions In Last Month</h3>
				  			<div class="green_bg">
				  				<div><%= get_transaction_count_total(Time.now-1.month,Time.now) %></div>
				  			</div>
				  		</div>
		  				<div class="clearfix"></div>
		  			</div>
			  		<div class="top_space">
				  		<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12"> 
				  		<h3>Amount Earned In Last Month</h3>
				  			<div id="chart_amount" style="width:100%; height:400px;">
				  			</div>
				  		</div>			  		
				  		<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
				  			<h3>Total Amount Earned In Last Month</h3>
				  			<div class="green_bg blue_bg">
				  				<div>
				  					<div><span>&#8377;</span>
				  					<%= get_transaction_amount_total(Time.now-1.month,Time.now) %>
				  					</div>
				  				</div>
				  			</div>
				  		</div>
			  			<div class="clearfix"></div>
		  			</div>
			  	</div>
		  	</div><!--dashboard_outer ends-->
		</div>
  	</div>
</section> 
       
<div id="popDiv" class="ontop">
	<table cellpadding="4" cellspacing="4" id="popup">
		<tr>
			<td align="right">
				<a title="Click here to close the pop-up" href="#" onClick="hide('popDiv')">X</a>
			</td>
		</tr>
		<tr>
			<td align="center" style="font-weight:bold">
				Payment Details
			</td>
		</tr>
		<tr>
			<td>
				Payment Date: <%= Date.today.strftime("%d/%m/%y") %>
				<input type="hidden" value="<%= DateTime.now %>" id="payment_timestamp" name="payment_timestamp">
			</td>
		</tr>
		<tr>
			<td>
				Transaction Type
				<select name="transaction_type" id="transaction_type">
					<option value="">Select Type</option>	
				  	<option value="cash">Cash</option>
				  	<option value="imps">IMPS</option>
				  	<option value="paymentgateway">PaymentGateway</option>
				  	<option value="emv">EMV</option>
				</select>
				<input type="hidden" id="tid" name="tid">
			</td>
		</tr>
		<tr>
			<td>
				Transaction Details <br/>
				<textarea name="transaction_details" id="transaction_details" placeholder="Enter transaction details here..." class="transaction_area"></textarea>
			</td>
		</tr>

		<tr>
			<td id="button" align="center">
				<input type="submit" value="Submit">
			</td>
		</tr>
	</table>
</div>


<script type="text/javascript">

	$( document ).ready(function() {
	    $('#merchant_index').dataTable();
	});

	$(".popup").click(function(){
		var val = $("#tid").val($(this).attr('id'));
	})

	$("#button").click(function() {
		var tid = $("#tid").val();
		var date = $("#payment_timestamp").val();
		var type = $("#transaction_type").val();
		var details = $("#transaction_details").val();
		if (type != "" && details != ""){
		   	$.ajax({
		   	url: "/dashboard/update_transaction",
		   	type: "POST",
		   	data: {"date" : date, "type" : type, "details" : details, "tid" : tid},
		   	dataType: "json",
		   	success: function(data) {
		   		alert("Successfully updated the status")
		        location.reload();
		     	}
		   	});
		}
		else if (type == "" ){
			alert("Please select payment type");
		}
		else{
			alert("Please provide the payment details");
		}

	});

	function pop(div) {
		document.getElementById(div).style.display = 'block';
	}
	function hide(div) {
		document.getElementById(div).style.display = 'none';
	}
		//To detect escape button
	document.onkeydown = function(evt) {
		evt = evt || window.event;
		if (evt.keyCode == 27) {
			hide('popDiv');
		}
	};


	$(function () {
	    $('#chart').highcharts({
	        chart: {
	            type: 'line'
	        },
	        title: {
	            text: 'Monthly Total Transactions'
	        },
	        xAxis: {
	        	type: 'datetime',
	            dateTimeLabelFormats: { 
	                month: '%d. %b',
	                year: '%b'
	            },
	            title: {
	                text: 'Date'
	            }
	        },
	        yAxis: {
	            title: {
	                text: 'Number Of Transactions'
	            },
	            min: 0
	        },
	        tooltip: {
	            pointFormat: '{point.y:.0f}'
	        },

	        plotOptions: {
	            spline: {
	                marker: {
	                    enabled: true
	                }
	            }
	        },

	        series: [{
	            name: 'Transactions',
	            data: <%= get_transaction_count(Time.now-1.month,Time.now) %>
	        }]
	    });
	});

	$(function () {
	    $('#chart_amount').highcharts({
	        chart: {
	            type: 'line'
	        },
	        title: {
	            text: 'Monthly Earned Transactions'
	        },
	        xAxis: {
	        	type: 'datetime',
	            dateTimeLabelFormats: { // don't display the dummy year
	                month: '%d. %b',
	                year: '%b'
	            },
	            title: {
	                text: 'Date'
	            }
	        },
	        yAxis: {
	            title: {
	                text: 'Amount (Rs)'
	            },
	            min: 0
	        },
	        tooltip: {
	            pointFormat: 'Rs. {point.y:.0f}'
	        },

	        plotOptions: {
	            spline: {
	                marker: {
	                    enabled: true
	                }
	            }
	        },

	        series: [{
	            name: 'Transactions',
	            data: <%= get_transaction_amount(Time.now-1.month,Time.now) %>
	        }]
	    });
	});


</script>

app/views/dashboard/merchant_detail.html.erb
<section>
  	<div class="container">
  		<div class="padding_inner details_lookup">
		  	<h1>Merchant (<%=@merchant.merchant_uniq_id.upcase%>)</h1>
	  		<!--tab_menu ends-->	  				  	
		  	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
			  	<div class="merchant_details">
			  		<div class="row">
				  		<h2>Merchant Details</h2>
				  		<table>
				  			<tr>
				  				<td>First Name:</td>
				  				<td> <%= @merchant.first_name%></td>
				  			</tr>
				  			<tr>
				  				<td>Last Name: </td>
				  				<td>	
				  					<%= @merchant.last_name%>		  					
							  	</td>
				  			</tr>
				  			<tr>
				  				<td>Email Id:</td>
				  				<td>
				  					<%= @merchant.email_address%>			  			
				  				</td>
				  			</tr>	
				  			<tr>
				  				<td>Phone Number:</td>
				  				<td>
				  					<%= @merchant.phone_number%>
							  	</td>
				  			</tr>
				  			<tr>
				  				<td>Age:</td>
				  				<td>
				  					<%= @merchant.age%>
							  	</td>
				  			</tr>
				  			<tr>
				  				<td>Sex:</td>
				  				<td>
				  					<%= @merchant.sex%>
							  	</td>
				  			</tr>		  			
						</table>
			  		</div>
		  		</div>
		  	</div>

		  	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		  		<div class="merchant_details business_details">
			  		<div class="row">
				  		<h2>Business Details</h2>
				  		<table>
				  			<tr>
				  				<td>Business Name:</td>
				  				<td><%= @merchant.business_name%></td>
				  			</tr>
				  			<tr>
				  				<td>Business Type:</td>
				  				<td><%= @merchant.business_type%></td>
				  			</tr>
				  			<tr>
				  				<td>Industry Type:</td>
				  				<td><%= @merchant.industry_type %></td>
				  			</tr>	
				  			<tr class="add_top">
				  				<td>Address:</td>
				  				<td><%= @merchant.business_address%></td>
				  			</tr>	
				  			<tr>
				  				<td>Status:</td>
				  				<td>
				  					<b style="color: red;" ><%= @merchant.status.upcase unless @merchant.status.nil? %></b>
				  				</td>
				  			</tr>			  			 			
						</table>
			  		</div>
		  		</div>
		  	</div>
		  	<div class="clearfix"></div>

		  	<div class="kyc_details">
			  	<h2>KYC Details</h2>
			  	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				  	<div class="merchant_details">
				  		<div class="row">
					  		<table>
					  			<tr class="kyc_txt">
					  				<td>
					  					KYC Submitted
									</td>
					  				<td>
					  					<% if @merchant.is_kyc_submitted != true %>
											No
										<% else %>
											Yes
										<% end %>
									</td>
					  			</tr>
					  			<tr>
					  				<td>
										Address Proof:
					  				</td>
					  				<td><%= image_tag @merchant.address_proof.url %></td>
					  			</tr>
					  			<tr>
					  				<td>ID Proof:</td>
					  				<td><%= image_tag @merchant.id_proof.url %></td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Business Address Proof:
					  				</td>
					  				<td>
					  					<%= image_tag @merchant.business_address_proof.url %>
					  				</td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Business ID Proof:
					  				</td>
					  				<td> 
					  					<%= image_tag @merchant.business_id_proof.url %>
					  				</td>
					  			</tr>
					  		</table>
				  		</div>
				  	</div>
			  	</div>	

			  	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				  	<div class="merchant_details business_details given_id">
				  		<div class="row">
					  		<table>			  			
					  			<tr>
					  				<td>Given Address Proof:</td>
					  				<td><%= @merchant.given_address_proof %></td>
					  			</tr>
					  			<tr>
					  				<td>Given Id Proof:</td>
					  				<td><%= @merchant.given_id_proof %></td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Given Business Address Proof:
					  				</td>
					  				<td><%= @merchant.given_business_address_proof %></td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Given Business Id Proof:  
					  				</td>
					  				<td><%= @merchant.given_business_id_proof %></td>
					  			</tr>
					  		</table>
				  		</div>
				  	</div>
			  	</div>
			  	<div class="clearfix"></div>			  	
	  		</div>
			  
		  	<div class="merchant_device_details">
			  	<h1>Device Details</h1>
			  	<div class="merchant_table table-responsive">
			  		<table class="table text-center display" id="merchant_device">
			  			<thead>
						    <tr>
					      		<th>Terminal ID</th>
					      		<th>Phone Number</th>
					      		<th>Serial Number</th>
						      	<th>Device Type</th>
						      	<th>Device Status</th>
						    </tr>
					  	</thead>
					  	<tbody>
						  	<% @merchant_device.each do |device| %>
							    <tr>
						      		<td align="center"><%= device.terminal_id %></td>
						      		<td align="center"><%= device.sim_phone_number %> </td>    
						      		<td align="center"><%= device.device_serial_number %></td>
							      	<td align="center"><%= device.device_make %></td>
							      	<td align="center"><%= device.device_status.upcase unless device.device_status.nil? %></td>
							    </tr>
						  	<% end %>
					  	</tbody>
			  		</table>
			  	</div>
	  		</div>
		</div>
	</div>
</section>

<script type="text/javascript">
  $('#merchant_device').dataTable();
</script>

app/views/dashboard/transaction.html.erb
<section>
  	<div class="container">
  		<div class="padding_inner">
	  		<h1>Transactions</h1>		  		
		  	<div class="merchant_table table-responsive dash_transaction">
		  		<table class="table text-center display" id="merchant_transaction">
					<thead>
							<tr>
								<th>
									Date
								</th>
								<th>
									Amount
								</th>
								<th>
									Payment Status
								</th>
								<th>
									Device
								</th>
								<th>
									Update Payment Status
								</th>
							</tr>
						</thead>
						<tbody>
							<% @merchant_transaction.each do |transaction_list| %>
								<tr>
									<td>
										<%= transaction_list.transaction_timestamp.strftime("%d/%m/%y") unless transaction_list.transaction_timestamp.nil? %>
									</td>
									<td>
										<%= transaction_list.amount %>
									</td>
									<% if transaction_list.transaction_status == "paid" %>
										<td align="center" class="active">
											<%= transaction_list.transaction_status.upcase unless transaction_list.transaction_status.nil? %>
										</td>
									<% else %>
										<td align="center" class="pending">
											<%= transaction_list.transaction_status.upcase unless transaction_list.transaction_status.nil? %>
										</td>
									<% end %>
									<td>
										<%= transaction_list.device.device_serial_number %>
									</td>
									<td> 
									<div class="button_device">
										<% if transaction_list.transaction_status == "pending"%>

											<span style="cursor: pointer;" onClick="pop('popDiv')" class="popup btn btn-success user_pay_btn" id="<%=transaction_list.id%>">Paid</span>

											<%= link_to 'Cancelled',{:controller => :dashboard, :action => :transaction_cancel, :id => transaction_list.id},:class=> "btn btn-danger" , data: {confirm: "Are you sure!"} %>

										<% end %>
										</div>
									</td>
								</tr>
							<% end %>
						</tbody>
		  		</table>
		  	</div><!--merchant_table ends-->
		</div>
  	</div>
</section> 
   
<div id="popDiv" class="ontop">
	<table cellpadding="4" cellspacing="4" id="popup">
		<tr>
			<td align="right">
				<a title="Click here to close the pop-up" href="#" onClick="hide('popDiv')">X</a>
			</td>
		</tr>
		<tr>
			<td align="center" style="font-weight:bold">
				Payment Details
			</td>
		</tr>
		<tr>
			<td>
				Payment Date: <%= Date.today.strftime("%d/%m/%y") %>
				<input type="hidden" value="<%= DateTime.now %>" id="payment_timestamp" name="payment_timestamp">
			</td>
		</tr>
		<tr>
			<td>
				Transaction Type
				<select name="transaction_type" id="transaction_type">
					<option value="">Select Type</option>	
				  	<option value="cash">Cash</option>
				  	<option value="imps">IMPS</option>
				  	<option value="paymentgateway">PaymentGateway</option>
				  	<option value="emv">EMV</option>
				</select>
				<input type="hidden" id="tid" name="tid">
			</td>
		</tr>
		<tr>
			<td>
				Transaction Details <br/>
				<textarea name="transaction_details" id="transaction_details" placeholder="Enter transaction details here..." class="transaction_area"></textarea>
			</td>
		</tr>

		<tr>
			<td id="button" align="center">
				<input type="submit" value="Submit">
			</td>
		</tr>
	</table>
</div>
	

<script type="text/javascript">
	$('#merchant_transaction').dataTable();

	$(".popup").click(function(){
		var val = $("#tid").val($(this).attr('id'));
	})

	$("#button").click(function() {
		var tid = $("#tid").val();
		var date = $("#payment_timestamp").val();
		var type = $("#transaction_type").val();
		var details = $("#transaction_details").val();
		if (type != "" && details != ""){
		   	$.ajax({
		   	url: "/dashboard/update_transaction",
		   	type: "POST",
		   	data: {"date" : date, "type" : type, "details" : details, "tid" : tid},
		   	dataType: "json",
		   	success: function(data) {
		   		alert("Successfully updated the status")
		        location.reload();
		     	}
		   	});
		}
		else if (type == "" ){
			alert("Please select payment type");
		}
		else{
			alert("Please provide the payment details");
		}

	});

	function pop(div) {
		document.getElementById(div).style.display = 'block';
	}
	function hide(div) {
		document.getElementById(div).style.display = 'none';
	}
		//To detect escape button
	document.onkeydown = function(evt) {
		evt = evt || window.event;
		if (evt.keyCode == 27) {
			hide('popDiv');
		}
	};

</script>