config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users

  namespace :epsadmin do 
    resources :merchants do
    get '/merchant_status' => "merchants#merchant_status_check"
     get '/transaction' => "merchants#transaction",:as => :transaction
    get '/transaction_status' => "merchants#transaction_status_check"
      resources :invoices
     get '/invoice_status' => "invoices#invoice_status_check"
      resources :devices do 
         get '/device_status' => "devices#device_status_check"
      end
    end

    post 'admins/update_user_status' => 'admins#update_user_status'
    resources :admins
  end

  get 'admin_dashboard/all_device'
  get 'admin_dashboard/all_invoice'
  get 'admin_dashboard/individual_device/:id' => "admin_dashboard#individual_device",:as => :individual_device, via: [:get,:post]

  get 'dashboard/index'
  get 'dashboard/transaction'
  get 'dashboard/billing'
  get '/dashboard/billing_individual/:id' => 'dashboard#billing_individual', :as => :dashboard_billing_individual 
  get 'dashboard/merchant_detail'
  post '/dashboard/update_transaction' => 'dashboard#update_transaction'
  get '/dashboard/transaction_cancel/:id' => 'dashboard#transaction_cancel', :as => :dashboard_transaction_cancel


  ##API RELATED ROUTES
  namespace :api do
    namespace :v1 do
      #get "/falconplus/validate_device" => "falcon_plus#validate_device"
      post "/falconplus/send_otp"=>"falcon_plus#send_otp"
      post "/falconplus/save_customer"=>"falcon_plus#save_customer"
      post "/falconplus/create_transaction"=>"falcon_plus#create_transaction"
      get "/falconplus/get_transaction_by_id"=>"falcon_plus#get_transaction_by_id"
      post "/falconplus/update_transaction_by_id"=>"falcon_plus#update_transaction_by_id"
      #get "/falconplus/pending_transaction_by_code"=>"falcon_plus#pending_transaction_by_code"
      #get "/falconplus/pending_transaction_by_terminal_id"=>"falcon_plus#pending_transaction_by_terminal_id"
      #get "/falconplus/pending_transaction_by_id"=>"falcon_plus#pending_transaction_by_id"
      
     # match "/falconplus/update_transaction_by_terminal_id"=>"falcon_plus#update_transaction_by_terminal_id", via: [:put,:post]
    end
  end
end

app/controllers/epsadmin/admins_controller.rb
class Epsadmin::AdminsController < ApplicationController

  before_filter :check_admin, :check_not_merchant
  def index
    @epsadmin_users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @epsadmin_users }
    end
  end

  def show
    @epsadmin_user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @epsadmin_user }
    end
  end

  def new
    @epsadmin_user = User.new
    respond_to do |format|
      format.html
      format.json { render json: @epsadmin_user }
    end
  end

  def edit
    @epsadmin_user = User.find(params[:id])
  end

  def create
    @epsadmin_user = User.new(user_params)

    respond_to do |format|
      if @epsadmin_user.save
        format.html { redirect_to epsadmin_admins_path, notice: 'Admin was successfully created.' }
        format.json { render json: epsadmin_admins_path, status: :created, location: @epsadmin_user }
      else
        format.html { render action: "new" }
        format.json { render json: epsadmin_admins_path.errors, status: :unprocessable_entity }
      end
      UserMailer.welcome_admin(@epsadmin_user).deliver
    end
  end

  def update
    @epsadmin_user = User.find(params[:id])

    respond_to do |format|
      if @epsadmin_user.update_attributes(user_params)
        format.html { redirect_to epsadmin_admin_path, notice: 'Admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: epsadmin_admin_path.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @epsadmin_user = User.find(params[:id])
    @epsadmin_user.destroy
    respond_to do |format|
      format.html { redirect_to epsadmin_admins_path , notice: 'Admin was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def update_user_status
    @update_user_status = User.find(params[:uid])
    if params[:stat] == "Disable"
      @update_user_status.update_attributes(:disabled => true)
    else
      @update_user_status.update_attributes(:disabled => false)
    end
    respond_to do |format|
      format.html { redirect_to epsadmin_admins_path, notice: 'Status was successfully updated.'}
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @epsadmin_user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:full_name,:email,:password, :password_confirmation ,:role)
    end
  
end

app/controllers/epsadmin/devices_controller.rb
class Epsadmin::DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  before_action :get_merchant
  before_filter :check_not_merchant
  def index
    add_breadcrumb "Merchants", epsadmin_merchants_path
    add_breadcrumb "#{@merchant.first_name}", epsadmin_merchant_path(@merchant.id)
    add_breadcrumb "Devices","#"
    @epsadmin_devices = @merchant.devices
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @epsadmin_devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @epsadmin_device = Device.find(params[:id])
    add_breadcrumb "Merchants", epsadmin_merchants_path
    add_breadcrumb "#{@epsadmin_device.merchant.first_name}", epsadmin_merchant_path(@epsadmin_device.merchant.id)
    add_breadcrumb "Devices",epsadmin_merchant_devices_path(@merchant.id)
    add_breadcrumb "#{@epsadmin_device.terminal_id}",""
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @epsadmin_device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    add_breadcrumb "Merchants", epsadmin_merchants_path
    add_breadcrumb "#{@merchant.first_name}", epsadmin_merchant_path(@merchant.id)
    add_breadcrumb "Devices",epsadmin_merchant_devices_path(@merchant.id)
    add_breadcrumb "Add New Device",""
    @epsadmin_device = Device.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @epsadmin_device }
    end
  end

  # GET /devices/1/edit
  def edit
    @epsadmin_device = Device.find(params[:id])
    add_breadcrumb "Merchants", epsadmin_merchants_path
    add_breadcrumb "#{@epsadmin_device.merchant.first_name}", epsadmin_merchant_path(@epsadmin_device.merchant.id)
    add_breadcrumb "Devices",epsadmin_merchant_devices_path(@merchant.id)
    add_breadcrumb "#{@epsadmin_device.terminal_id}",epsadmin_merchant_device_path
    add_breadcrumb "Edit",""
  end

  # POST /devices
  # POST /devices.json
  def create
    add_breadcrumb "Merchants", epsadmin_merchants_path
    add_breadcrumb "#{@merchant.first_name}", epsadmin_merchant_path(@merchant.id)
    add_breadcrumb "Devices",epsadmin_merchant_devices_path(@merchant.id)
    add_breadcrumb "Add New Device",""
    @epsadmin_device = Device.new(device_params)
     @epsadmin_device.modifier_id=current_user.id
    #Generation of terminal id
    @epsadmin_device.terminal_id = params[:device][:device_serial_number].last(3) + params[:device][:merchant_id].first(3)
    #End
    respond_to do |format|
      if @epsadmin_device.save
        format.html { redirect_to epsadmin_merchant_devices_path, notice: 'Device was successfully created.' }
        format.json { render json: epsadmin_merchant_devices_path, status: :created, location: @epsadmin_device }
      else
        format.html { render action: "new" }
        format.json { render json: @epsadmin_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @epsadmin_device = Device.find(params[:id])
    add_breadcrumb "Merchants", epsadmin_merchants_path
    add_breadcrumb "#{@epsadmin_device.merchant.first_name}", epsadmin_merchant_path(@epsadmin_device.merchant.id)
    add_breadcrumb "Devices",epsadmin_merchant_devices_path(@merchant.id)
    add_breadcrumb "#{@epsadmin_device.terminal_id}",""
    add_breadcrumb "Edit",""
    respond_to do |format|
      if @epsadmin_device.update_attributes(device_params)
        format.html { redirect_to epsadmin_merchant_device_path, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: epsadmin_merchant_device_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @epsadmin_device = Device.find(params[:id])
    if @epsadmin_device.device_status == "pending"
      @epsadmin_device.destroy
      respond_to do |format|
        format.html { redirect_to epsadmin_merchant_devices_path }
        format.json { head :no_content }
      end
    else
        respond_to do |format|
          format.html { redirect_to epsadmin_merchant_device_path, notice: 'Device status must be in pending state to delte/remove it' }
          format.json { head :no_content }
        end
    end
  end

  def device_status_check
    mid=Device.where(:id=>params[:device_id]).first
    if params[:st] == "activate"
      @res=mid.activate
    elsif params[:st] == "inactivate"
      @res=mid.inactivate
    elsif params[:st] == "deactivate"
      @res=mid.deactivate
    else
      @res=mid
    end 
    respond_to do |format|
      format.html
      format.json { render :json=>@res} 
    end
  end

  private

  def device_params
    params.require(:device).permit(:device_serial_number, :sim_phone_number, :sim_msid_number, :device_make, :device_display, :bank_mmid, :device_status, :terminal_id, :setup_cost, :monthly_cost, :transaction_cost, :parent_id, :merchant_id,:modifier_id,:version_comments)
  end

  def get_merchant
    @merchant = Merchant.where(:id => params[:merchant_id]).first
  end

end

app/controllers/epsadmin/invoices_controller.rb
class Epsadmin::InvoicesController < ApplicationController
  # GET /invoices
  # GET /invoices.json
  before_action :get_merchant, :get_subscription
  before_filter :check_not_merchant

  def index
    add_breadcrumb "Merchants", epsadmin_merchants_path
    add_breadcrumb "#{@merchant.first_name}", epsadmin_merchant_path(@merchant.id)
    add_breadcrumb "Invoices",""
    @epsadmin_invoices = @subscription.invoices
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @epsadmin_invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @epsadmin_invoice = Invoice.find(params[:id])
    add_breadcrumb "Merchants", epsadmin_merchants_path
    add_breadcrumb "#{@merchant.first_name}", epsadmin_merchant_path(@merchant.id)
    add_breadcrumb "Invoices", epsadmin_merchant_invoices_path
    add_breadcrumb "#{@epsadmin_invoice.invoice_number}",""
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @epsadmin_invoice }
    end
  end


  # GET /invoices/new
  # GET /invoices/new.json
  def new
    add_breadcrumb "Merchants", epsadmin_merchants_path
    add_breadcrumb "#{@merchant.first_name}", epsadmin_merchant_path(@merchant.id)
    add_breadcrumb "Invoices",epsadmin_merchant_invoices_path
    add_breadcrumb "Add New Invoice",""
    @epsadmin_invoice = Invoice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @epsadmin_invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
    @epsadmin_invoice = Invoice.find(params[:id])
    add_breadcrumb "Merchants", epsadmin_merchants_path
    add_breadcrumb "#{@merchant.first_name}", epsadmin_merchant_path(@merchant.id)
    add_breadcrumb "Invoices",epsadmin_merchant_devices_path(@merchant.id)
    add_breadcrumb "#{@epsadmin_invoice.invoice_number}",epsadmin_merchant_invoice_path
    add_breadcrumb "Edit",""
  end

  # POST /invoices
  # POST /invoices.json
  def create
    add_breadcrumb "Merchants", epsadmin_merchants_path
    add_breadcrumb "#{@merchant.first_name}", epsadmin_merchant_path(@merchant.id)
    add_breadcrumb "Invoices",epsadmin_merchant_invoices_path
    add_breadcrumb "Add New Invoice",""
    @epsadmin_invoice = Invoice.new(invoice_params)
    @epsadmin_invoice.modifier_id=current_user.id
    @epsadmin_invoice.tax = params[:invoice][:tax]
    @epsadmin_invoice.invoice_amount = params[:invoice][:invoice_amount]

    respond_to do |format|
      if @epsadmin_invoice.save
        (0...params[:select].values.length).each do |l|
          InvoiceLineItem.create(:description => params[:desc].values[l] ,:amount => params[:amt].values[l], :line_item_type =>  params[:select].values[l], :invoice_id => @epsadmin_invoice.id )
        end
        format.html { redirect_to epsadmin_merchant_invoices_path, notice: 'Invoice was successfully created.' }
        format.json { render json: epsadmin_merchant_invoices_path, status: :created, location: @epsadmin_invoice }
      else
        format.html { render action: "new" }
        format.json { render json: epsadmin_invoice.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /invoices/1
  # PUT /invoices/1.json
  def update
    @epsadmin_invoice = Invoice.find(params[:id])
    add_breadcrumb "Merchants", epsadmin_merchants_path
    add_breadcrumb "#{@merchant.first_name}", epsadmin_merchant_path(@merchant.id)
    add_breadcrumb "Invoices",epsadmin_merchant_devices_path(@merchant.id)
    add_breadcrumb "#{@epsadmin_invoice.invoice_number}",epsadmin_merchant_invoice_path
    add_breadcrumb "Edit",""

    respond_to do |format|
      if @epsadmin_invoice.update_attributes(invoice_params)

        if params[:select].present?
          @epsadmin_invoice.invoice_line_items.delete_all
          (0...params[:select].values.length).each do |l|
            InvoiceLineItem.create(:description => params[:desc].values[l] ,:amount => params[:amt].values[l], :line_item_type =>  params[:select].values[l], :invoice_id => @epsadmin_invoice.id )
          end
        end

        format.html { redirect_to epsadmin_merchant_invoice_path, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: epsadmin_merchant_invoice_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @epsadmin_invoice = Invoice.find(params[:id])
    @epsadmin_invoice.destroy

    respond_to do |format|
      format.html { redirect_to epsadmin_merchant_invoices_path }
      format.json { head :no_content }
    end
  end
def invoice_status_check
    mid=Invoice.where(:id=>params[:tid]).first
    if params[:cls].include?"waive"
    mid.update_attribute("remarks",params['details'])
    @res=mid.waive
    elsif params[:cls].include?"popup"
    mid.update_attributes(:paid_date => params[:date] ,:payment_details => params[:details], :paid_via =>  params[:type])
    @res=mid.pay
  elsif params[:cls].include?"cancel"
    mid.update_attribute("remarks",params['details'])
    @res=mid.cancel
  end
    respond_to do |format|
     format.html
     format.json { render :json=>@res} 
   end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:invoice_number, :invoice_date, :business_name, :address, :amount, :tax, :invoice_type, :status, :paid_date, :payment_details, :remarks, :paid_via, :device_id, :subscription_id,:invoice_amount,:modifier_id,:version_comments)
  end

  def get_merchant
    @merchant = Merchant.where(:id => params[:merchant_id]).first
  end

  def get_subscription
    @subscription = Subscription.where(:merchant_id => params[:merchant_id]).first
  end


end

app/helpers/epsadmin/admins_helper.rb
module Epsadmin::AdminsHelper
end

app/helpers/epsadmin/merchants_helper.rb
module Epsadmin::MerchantsHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/epsadmin/merchants/edit.html.erb
<div class="container back_outer">
	<%= link_to 'Cancel', epsadmin_merchant_path, :class=>"btn back_btn" %>
</div>

<%= render 'form' %>

app/views/epsadmin/merchants/index.html.erb
<section>
	<div class="container">
		<div class="padding_inner">
			<h1>Merchants Management</h1>
			<%= render_breadcrumbs :separator => ' / ' %>
  		 	<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>	  		
		  	<div class="pull-right">
	  			<%= link_to 'Add New Merchant', new_epsadmin_merchant_path, :class => "btn btn-primary" %>
		  	</div>
		  	<div class="clearfix"></div>
			<div class="merchant_table table-responsive">
				<table id="merchant" class="display table text-center">
				    <thead>
					  <tr>
					    <th>Merchant ID</th>
					    <th>Business Name</th>
					    <th>Name</th>
					    <th>Phone</th>
					    <th>Email</th>
					    <th>Status</th>
					  </tr>
				    </thead>
				    <tbody>
					  <% @epsadmin_merchants.each do |merchant| %>
					    <tr>
					      <td align="center"><%= link_to merchant.merchant_uniq_id.upcase, epsadmin_merchant_path(merchant) %></td>
					      <td align="center"><%=merchant.business_name%></td>
					      <td align="center"><%=merchant.first_name%>&nbsp;<%=merchant.last_name %></td>
					      <td align="center"><%=merchant.phone_number%></td>
					      <td align="center"><%=merchant.email_address%></td>
					      <td align="center"><%=merchant.status.upcase unless merchant.status.nil? %></td>
					    </tr>
					  <% end %>
					</tbody>
				</table>
		  	</div><!--merchant_table ends-->
		</div>
  	</div>
</section>

<script type="text/javascript">
  $('#merchant').dataTable();
</script>

app/views/epsadmin/merchants/new.html.erb
 
<div class="container back_outer">
  <%= link_to 'Back', epsadmin_merchants_path, :class=>"btn back_btn" %>
</div>

<%= render 'form' %>

app/views/epsadmin/merchants/show.html.erb
	
<section>
  	<div class="container">
  		<div class="padding_inner details_lookup">
		  	<h1>Merchant (<%=@epsadmin_merchant.merchant_uniq_id.upcase%>)</h1>
  		 	<%= render_breadcrumbs :separator => ' / ' %>
  		 	<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
	  		<div class="tab_menu">
	  			<ul>
	  				<li><%=link_to "Details",epsadmin_merchants_path, :class=>"active"%></li>
	  				<li><%=link_to "Devices",epsadmin_merchant_devices_path(@epsadmin_merchant.id)%></li>
	  				<li><%= link_to 'Transactions', epsadmin_merchant_transaction_path(@epsadmin_merchant.id) %></li>
	  				<li><%= link_to 'Invoice', epsadmin_merchant_invoices_path(@epsadmin_merchant.id) %></li>
	  			</ul>
	  			<div class="clearfix"></div>
	  		</div>
	  		<!--tab_menu ends-->	  				  	
		  	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
			  	<div class="merchant_details">
			  		<div class="row">
				  		<h2>Merchant Details</h2>
				  		<table>
				  			<tr>
				  				<td>First Name:</td>
				  				<td> <%= @epsadmin_merchant.first_name%></td>
				  			</tr>
				  			<tr>
				  				<td>Last Name: </td>
				  				<td>	
				  					<%= @epsadmin_merchant.last_name%>		  					
							  	</td>
				  			</tr>
				  			<tr>
				  				<td>Email Id:</td>
				  				<td>
				  					<%= @epsadmin_merchant.email_address%>			  			
				  				</td>
				  			</tr>	
				  			<tr>
				  				<td>Phone Number:</td>
				  				<td>
				  					<%= @epsadmin_merchant.phone_number%>
							  	</td>
				  			</tr>
				  			<tr>
				  				<td>Age:</td>
				  				<td>
				  					<%= @epsadmin_merchant.age%>
							  	</td>
				  			</tr>
				  			<tr>
				  				<td>Sex:</td>
				  				<td>
				  					<%= @epsadmin_merchant.sex%>
							  	</td>
				  			</tr>		  			
						</table>
			  		</div>
		  		</div>
		  	</div>

		  	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		  		<div class="merchant_details business_details">
			  		<div class="row">
				  		<h2>Business Details</h2>
				  		<table>
				  			<tr>
				  				<td>Business Name:</td>
				  				<td><%= @epsadmin_merchant.business_name%></td>
				  			</tr>
				  			<tr>
				  				<td>Business Type:</td>
				  				<td><%= @epsadmin_merchant.business_type%></td>
				  			</tr>
				  			<tr>
				  				<td>Industry Type:</td>
				  				<td><%= @epsadmin_merchant.industry_type %></td>
				  			</tr>	
				  			<tr class="add_top">
				  				<td>Address:</td>
				  				<td><%= @epsadmin_merchant.business_address%></td>
				  			</tr>	
				  			<tr>
				  				<td>Status:</td>
				  				<td>
				  					<% if @epsadmin_merchant.status == "active" %>
			  							<b class="active">
		  									<%= @epsadmin_merchant.status.upcase unless @epsadmin_merchant.status.nil? %>
		  								</b>
	  								<% else %>
										<b class="pending">
		  									<%= @epsadmin_merchant.status.upcase unless @epsadmin_merchant.status.nil? %>
		  								</b>
	  								<% end %>
				  				</td>
				  			</tr>			  			 			
						</table>
			  		</div>
		  		</div>
		  	</div>
		  	<div class="clearfix"></div>

		  	<div class="kyc_details">
			  	<h2>KYC Details</h2>
			  	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				  	<div class="merchant_details">
				  		<div class="row">
					  		<table>
					  			<tr class="kyc_txt">
					  				<td>
					  					KYC Submitted
									</td>
					  				<td>
					  					<% if @epsadmin_merchant.is_kyc_submitted != true %>
											No
										<% else %>
											Yes
										<% end %>
									</td>
					  			</tr>
					  			<tr>
					  				<td>
										Address Proof:
					  				</td>
					  				<td><%= image_tag @epsadmin_merchant.address_proof.url %></td>
					  			</tr>
					  			<tr>
					  				<td>ID Proof:</td>
					  				<td><%= image_tag @epsadmin_merchant.id_proof.url %></td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Business Address Proof:
					  				</td>
					  				<td>
					  					<%= image_tag @epsadmin_merchant.business_address_proof.url %>
					  				</td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Business ID Proof:
					  				</td>
					  				<td> 
					  					<%= image_tag @epsadmin_merchant.business_id_proof.url %>
					  				</td>
					  			</tr>
					  		</table>
				  		</div>
				  	</div>
			  	</div>	

			  	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				  	<div class="merchant_details business_details given_id">
				  		<div class="row">
					  		<table>			  			
					  			<tr>
					  				<td>Given Address Proof:</td>
					  				<td><%= @epsadmin_merchant.given_address_proof %></td>
					  			</tr>
					  			<tr>
					  				<td>Given Id Proof:</td>
					  				<td><%= @epsadmin_merchant.given_id_proof %></td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Given Business Address Proof:
					  				</td>
					  				<td><%= @epsadmin_merchant.given_business_address_proof %></td>
					  			</tr>
					  			<tr>
					  				<td>
					  					Given Business Id Proof:  
					  				</td>
					  				<td><%= @epsadmin_merchant.given_business_id_proof %></td>
					  			</tr>
					  		</table>
				  		</div>
				  	</div>
			  	</div>
			  	<div class="clearfix"></div>			  	
	  		</div>

		  <div class="submit_space button_space text-center">
		  		<%= link_to 'Edit', edit_epsadmin_merchant_path, :class=>"btn btn-info", :disabled => false if is_merchant_editable?(@epsadmin_merchant.status) %>

		  		<%= link_to 'Destroy', epsadmin_merchant_path, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }, :disabled => false if is_merchant_deletable?(@epsadmin_merchant.status) %>

		  		<%= link_to 'Back', epsadmin_merchants_path, :class => "btn btn-info" %>
		  </div>
			  
			<!--status update-->
		  <div class="status_update text-center">
		  	<h3>Status Update</h3>

			<% if @epsadmin_merchant.status == "pending" %>
				<button type="button" id="activate" class="btn btn-success scheck">Activate</button> 
				<button type="button" id="inactivate" class="btn btn-warning" disabled>Inactivate</button> 
				<button type="button" id="cancel" class="btn btn-danger" disabled>Cancel</button> 
				<button type="button" id="close" class="btn btn-info" disabled>Close</button> 
			<% end %>

			<% if @epsadmin_merchant.status == "active" %>
				<button type="button" id="activate"  class="btn btn-success" disabled>Activated</button> 
				<button type="button" id="inactivate" class="btn btn-warning scheck">Inactivate</button> 
				<button type="button" id="cancel" class="btn btn-danger scheck">Cancel</button> 
				<button type="button" id="close" class="btn btn-info scheck">Closed</button> 
			<% end %>

			<% if @epsadmin_merchant.status == "inactive" %>
				<button type="button" id="activate"  class="btn scheck">Activate</button> 
				<button type="button" id="inactivate" class="btn btn-warning" disabled>Inactivated</button> 
				<button type="button" id="cancel" class="btn btn-danger scheck">Cancel</button> 
				<button type="button" id="close" class="btn btn-info scheck">Close</button> 
			<% end %>

			<% if @epsadmin_merchant.status == "cancelled" %>
				Account is currently cancelled.
			<% end %>
			<% if @epsadmin_merchant.status == "closed" %>
				Account is currently closed.
			<% end %>
		  </div>
			  <!--stats update ends-->
		</div>
  	</div>
  	
</section>



<script>
$(document).ready(function(){
    $('.scheck').click(function(){
    	var check = confirm("Are you sure?");
        if (check == true) {
    	var status= $(this).attr('id');
    	 // alert(status);
	$.ajax({
	type: "GET",
	url: '/epsadmin/merchants/<%=@epsadmin_merchant.id%>/merchant_status',
	data: {st: status},
	dataType: 'json',
 	success: function(data){
                  if(data == true)
                  	window.location.href='/epsadmin/merchants/<%=@epsadmin_merchant.id%>'; 
                  else
                  	alert("Device status should be in active.All the merchant fields should be present");
                  	return false;
                }
	});
   
}
else
	{
		return false;
	}
});
     });
</script>