config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users

  namespace :epsadmin do 
    resources :merchants do
    get '/merchant_status' => "merchants#merchant_status_check"
     get '/transaction' => "merchants#transaction",:as => :transaction
    get '/transaction_status' => "merchants#transaction_status_check"
      resources :invoices
     get '/invoice_status' => "invoices#invoice_status_check"
      resources :devices do 
         get '/device_status' => "devices#device_status_check"
      end
    end

    post 'admins/update_user_status' => 'admins#update_user_status'
    resources :admins
  end

  get 'admin_dashboard/all_device'
  get 'admin_dashboard/all_invoice'
  get 'admin_dashboard/individual_device/:id' => "admin_dashboard#individual_device",:as => :individual_device, via: [:get,:post]

  get 'dashboard/index'
  get 'dashboard/transaction'
  get 'dashboard/billing'
  get '/dashboard/billing_individual/:id' => 'dashboard#billing_individual', :as => :dashboard_billing_individual 
  get 'dashboard/merchant_detail'
  post '/dashboard/update_transaction' => 'dashboard#update_transaction'
  get '/dashboard/transaction_cancel/:id' => 'dashboard#transaction_cancel', :as => :dashboard_transaction_cancel


  ##API RELATED ROUTES
  namespace :api do
    namespace :v1 do
      #get "/falconplus/validate_device" => "falcon_plus#validate_device"
      post "/falconplus/send_otp"=>"falcon_plus#send_otp"
      post "/falconplus/save_customer"=>"falcon_plus#save_customer"
      post "/falconplus/create_transaction"=>"falcon_plus#create_transaction"
      get "/falconplus/get_transaction_by_id"=>"falcon_plus#get_transaction_by_id"
      post "/falconplus/update_transaction_by_id"=>"falcon_plus#update_transaction_by_id"
      #get "/falconplus/pending_transaction_by_code"=>"falcon_plus#pending_transaction_by_code"
      #get "/falconplus/pending_transaction_by_terminal_id"=>"falcon_plus#pending_transaction_by_terminal_id"
      #get "/falconplus/pending_transaction_by_id"=>"falcon_plus#pending_transaction_by_id"
      
     # match "/falconplus/update_transaction_by_terminal_id"=>"falcon_plus#update_transaction_by_terminal_id", via: [:put,:post]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Epspro</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<header>
		  	<div class="container">
		  		<div class="col-lg-2 col-md-2 col-sm-1 col-xs-12 logo">
		  			<a href="#" class="logo_txt">Logo</a>
		  		</div>
		  		<div class="col-lg-10 col-md-10 col-sm-11">	  
		  			<!--menu-->
		  			<nav class="navbar-default pull-left">       
				          <div class="navbar-header">
				            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">            
				              <span class="icon-bar"></span>
				              <span class="icon-bar"></span>
				              <span class="icon-bar"></span>
				            </button>          
				          </div>
				          <div id="navbar" class="navbar-collapse collapse">
				            <ul class="nav navbar-nav pull-right">
								<% if user_signed_in? %>
							 		<% if current_user.not_merchant? %>
								 	    <li><%=link_to "Merchants",epsadmin_merchants_path %></li>
					  					<li><%=link_to "Devices", admin_dashboard_all_device_path %></li>
					  					<li><%=link_to "Invoices", admin_dashboard_all_invoice_path %></li>
					  					<li><%=link_to "Users",epsadmin_admins_path if current_user.is_admin? %></li>
							 	    <% else %>
							 	    	<li><%=link_to "Dashboard", dashboard_index_path %></li>
							 	    	<li><%=link_to "Transactions", dashboard_transaction_path %></li>
							 	    	<li><%=link_to "Merchant Details", dashboard_merchant_detail_path %></li>
							 	    	<li><%=link_to "Billing", dashboard_billing_path %></li>
							    	<% end %>

							 	    <li><%= link_to "Change Password", edit_user_registration_path %></li>
							 	    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li> 
						 		<%end%>
				            </ul>
				          </div>       
		  			</nav>
		  			<!--menu ends-->	
		  			<div class="pull-right user_name">
		  				<% if user_signed_in? %>
		  					<img src="/assets/person_icon.png" alt="">
					 	<%end%>
			  			<span>
		  				 	<% if user_signed_in? %>
						 		Hi <%= current_user.full_name %>
						 	<%end%>
			  			</span>
		  			</div>  			
		  		</div>
		  		<div class="clearfix"></div>
		  	</div>
		</header>

	<%= yield %>

	</body>
</html>